#!/bin/bash
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -o /home/ryan/logs/${PBS_JOBNAME}.o${PBS_JOBID}.log
#PBS -e /home/ryan/logs/${PBS_JOBNAME}.e${PBS_JOBID}.err
#PBS -l walltime=150:00:00
#PBS -l mem=16gb
#PBS -N GAN_ryan_personal

/home/ryan/anaconda3/bin/python /home/ryan/software/CrossStitch/Crossstitch_GAN.py \
--indir /home/ryan/software/CrossStitch/data/Personal_Art_References/ \
--outdir /home/ryan/software/CrossStitch/out/Personal_Art_References/ \
--nsample 32
